### ISSUE TITLE
Add support for image pull secrets

### ISSUE THREAD

**Issue by anothertobi** [projectsyn/component-kyverno#50]
## Context
To verify the signature of images which are part of a private registry, the corresponding image pull secret needs to exist in the same namespace (see: https://kyverno.io/docs/writing-policies/verify-images/#using-private-registries).

The necessary additional argument (`--imagePullSecrets=name-of-the-secret`) can already be configured through the `extraArgs` parameter.

## Alternatives
Manually managing the image pull secrets would be the undesired alternative.

**Comment by simu** [comment]
Consider using https://syn.tools/commodore/reference/commodore-libjsonnet.html#_generateresourcesresources_resourcefn to implement secret rendering in the component.

**Comment by corvus-ch** [comment]
This is a feature we should potentially add to each and every component. @simu Any suggestions on how we could generalize this?

**Comment by simu** [comment]
> This is a feature we should potentially add to each and every component. @simu Any suggestions on how we could generalize this?

The only idea I've got off the top of my head is that we'd add some magic in Commodore which injects logic to render Secret resources in a component if `parameters.<component_name>.secrets` exists, but that doesn't feel right. Otherwise, it's pretty much a matter of adding 

```yaml
parameters:
  <component_name>:
    secrets: {}
```
in `class/defaults.yml` and

```jsonnet
local com = import 'lib/commodore.libjsonnet';
local kap = import 'lib/kapitan.libjsonnet';
local kube = import 'lib/kube.libjsonnet';
local inv = kap.inventory();
local params = inv.parameters.<component_name>;
{
  '00_secrets': com.generateResources(params.secrets, kube.Secret);
}
```
somewhere in the component Jsonnet
